name: Deploy Python app to EC2

on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'EC2 Instance ID'
        required: true
        type: string
      environment:
        description: 'Deployment environment (dev, prod)'
        required: true
        default: 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (full history for SHA)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git checkout $GIT_COMMIT_SHA later

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies FROM app/python/requirements.txt
      - name: Install dependencies
        run: |
          cd app/python  # <-- KEY CHANGE: Move to the Python app directory
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Now this path is correct

      # Steps 4-7: Security scans (same as before but run from app/python)
      - name: Run Safety (CVE Scan)
        run: |
          cd app/python  # <-- Run scans in the correct directory
          pip install safety
          safety check -r requirements.txt --full-report > safety_report.txt || true
        # ... rest of Safety/Bandit steps ...

      # Step 8: Deploy to EC2 (with corrected paths)
      - name: Deploy to EC2 via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: |
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

          # Send commands to EC2
          aws ssm send-command \
            --instance-ids "${{ github.event.inputs.instance_id }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands": [
                "cd /opt/myapp/app/python || exit 1",  # <-- Match EC2 directory structure
                "git fetch origin || exit 1",
                "git checkout $GIT_COMMIT_SHA || exit 1",
                "git pull origin main || exit 1",
                "python3 -m venv myapp --clear || exit 1",
                "source myapp/bin/activate || exit 1",
                "pip install -r requirements.txt || exit 1"  # Now this path works
              ]
            }'