name: Deploy Python app to EC2

on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'EC2 Instance ID'
        required: true
        type: string
      environment:
        description: 'Deployment environment (dev, prod)'
        required: true
        default: 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (updated to v4)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (updated to v4)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Safety
      - name: Run Safety (CVE Scan)
        run: |
          pip install safety
          safety check -r requirements.txt --full-report > safety_report.txt || true
        continue-on-error: true

      # Step 5: Upload Safety report (updated to v4)
      - name: Upload Safety scan report
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: safety_report.txt

      # Step 6: Run Bandit
      - name: Run Bandit (Security Scan)
        run: |
          pip install bandit
          bandit -r . -o bandit_report.html || true
        continue-on-error: true

      # Step 7: Upload Bandit report (updated to v4)
      - name: Upload Bandit scan report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit_report.html

      # Step 8: Deploy to EC2 via SSM (using AWS CLI directly)
      - name: Deploy to EC2 via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

          # Send commands via AWS SSM
          aws ssm send-command \
            --instance-ids "${{ github.event.inputs.instance_id }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands": [
              "cd /opt/myapp || exit 1",
              "git pull origin main || exit 1",
              "python3 -m venv myapp --clear || exit 1",
              "source myapp/bin/activate || exit 1",
              "pip install -r requirements.txt || exit 1"
            ]}'