name: Docker Build, Scan & Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/python/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx (required for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-qemu-action@v3

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t michaelkedey/jomacsdevsecops:latest -f app/containerization/Dockerfile app/python/

    # Install Trivy
    - name: Install Trivy
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb -o trivy.deb
        sudo dpkg -i trivy.deb

    # Scan the Docker image for vulnerabilities using Trivy
    - name: Scan Docker image for vulnerabilities
      id: trivy_scan
      run: |
        mkdir -p trivy-reports
        trivy image --no-progress --severity HIGH,CRITICAL --format json --output trivy-reports/scan-report.json michaelkedey/jomacsdevsecops:latest

    # Upload the Trivy scan report as an artifact (so you can download it later)
    - name: Upload Trivy scan report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-report
        path: trivy-reports/scan-report.json
    
    # If no vulnerabilities with high severity are found, push to Docker Hub
    - name: Push Docker image to Docker Hub
      if: ${{ success() }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push michaelkedey/jomacsdevsecops:latest
